'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const listeners=new Map(),drawCalls=[],burnDraws=[],elements=new Map();
const emit=(name,event={})=>{for(const fn of listeners.get(name)||[])fn(event)};
const on=(name,fn)=>{if(!listeners.has(name))listeners.set(name,[]);listeners.get(name).push(fn)};
function classes(){const values=new Set();return {add:x=>values.add(x),remove:x=>values.delete(x),contains:x=>values.has(x)}}
function element(id){if(!elements.has(id))elements.set(id,{style:{},classList:classes(),hidden:false,setAttribute(){},addEventListener:on,getContext(){return new Proxy({drawImage(...args){drawCalls.push(args)},fillText(...args){burnDraws.push(args)},bezierCurveTo(...args){burnDraws.push(args)},measureText:t=>({width:t.length*16}),createLinearGradient:()=>({addColorStop(){}}),createRadialGradient:()=>({addColorStop(){}})},{get:(t,k)=>t[k]||(()=>{})})}});return elements.get(id)}
class FakeAudio{constructor(src){this.src=src;this.paused=true;this.currentTime=0;this.events=new Map()}addEventListener(k,f){if(!this.events.has(k))this.events.set(k,new Set());this.events.get(k).add(f)}removeEventListener(k,f){this.events.get(k)?.delete(f)}play(){this.paused=false;return Promise.resolve()}pause(){this.paused=true}}
const document={getElementById:element,querySelector:element,addEventListener:on,body:{classList:classes()},fullscreenElement:null};
document.documentElement={requestFullscreen(){document.fullscreenElement=this;emit('fullscreenchange');return Promise.resolve()}};
document.exitFullscreen=()=>{document.fullscreenElement=null;emit('fullscreenchange');return Promise.resolve()};
const history={state:null,pushState(value){this.state=value},back(){this.state=null;emit('popstate')}};
const math=Object.create(Math);math.random=()=>.6;
const sandbox={window:{addEventListener:on,dispatchEvent:e=>emit(e.type,e)},document,history,screen:{orientation:{lock:async()=>{},unlock(){}}},matchMedia:query=>({matches:query==='(max-width: 1000px)'}),Audio:FakeAudio,Math:math,URLSearchParams,location:{search:'?test'},localStorage:{getItem(){return null},setItem(){}},requestAnimationFrame(){},console,CustomEvent:class{constructor(type,options){this.type=type;this.detail=options?.detail}},Image:class{set src(path){path=path.replace(/^optimized\//,'').replace('bg_image/optimized/','bg_image/').replace('.webp','.png');this.path=path;const png=fs.readFileSync(path.split('?')[0]);this.width=png.readUInt32BE(16);this.height=png.readUInt32BE(20);this.onload()}}};
vm.createContext(sandbox);for(const file of ['audio.js','game.js'])vm.runInContext(fs.readFileSync(file,'utf8'),sandbox);
(async()=>{
 await new Promise(setImmediate);const g=sandbox.window.__game;let count=0;
 function reset(){math.random=()=>.6;g.start();for(const key of ['nextPattern','nextAmbient','nextPirate','nextPirateGuarantee','nextIce','nextBaseball','nextBaseballGuarantee','nextBomb','nextGoblin','nextPortal','nextBonusJelly','nextSpeech'])g.state[key]=Infinity;g.state.nextItems.fill(Infinity);g.state.nextGuarantees.fill(Infinity);drawCalls.length=0}
 function step(seconds){let left=seconds;while(left>1e-10){const dt=Math.min(left,1/120);g.update(dt);left-=dt}}
 function test(name,fn){reset();fn();console.log('PASS',name);count++}
 const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`);
 test('burn draws body-height flames and a readable timer following airborne and sliding poses',()=>{g.hitPirateFire({});for(const airborne of [false,true]){g.state.p.y=airborne?160:0;g.state.p.jumps=airborne?1:0;burnDraws.length=0;g.draw();assert.ok(burnDraws.some(a=>typeof a[0]==='string'&&a[0].includes('화상 5.0초 · −2%/초')));assert.ok(burnDraws.some(a=>a.length===6&&a[5]<610-g.state.p.y-120))}g.state.p.y=0;g.state.p.jumps=0;g.state.p.hit=0;g.setSlide(true);g.draw();g.state.p.burn=0;burnDraws.length=0;g.draw();assert.ok(!burnDraws.some(a=>typeof a[0]==='string'&&a[0].startsWith('화상 ')))});
 test('invincibility warning starts at three seconds for each item and stops on expiry',()=>{for(const id of [5,6]){reset();g.acquire(id);g.state.buff[id]=3.01;assert.equal(g.invincibilityWarning(),false);step(.02);assert.equal(g.invincibilityWarning(),true);g.draw();g.pause();step(1);assert.equal(g.invincibilityWarning(),true);g.pause();step(3);assert.equal(g.invincibilityWarning(),false)}g.acquire(5);g.acquire(6);g.state.buff[5]=2;assert.equal(g.invincibilityWarning(),true)});
 test('baseball stun holds airborne position and velocity for 1.5 seconds',()=>{g.jump();step(.15);g.hitBaseball({x:220,y:500,w:64,h:64});const {x,y,vy}=g.state.p;step(1.49);near(g.state.p.x,x);near(g.state.p.y,y);near(g.state.p.vy,vy);g.jump();g.setSlide(true);near(g.state.p.vy,vy);step(.02);assert.equal(g.state.p.panic,0);assert.notEqual(g.state.p.y,y)});
 test('pirate fire causes immediate thirty damage and five independent two-point ticks',()=>{g.hitPirateFire({});assert.equal(g.state.energy,70);near(g.state.p.burn,5);step(.99);assert.equal(g.state.energy,70);g.draw();g.pause();step(2);assert.equal(g.state.energy,70);g.pause();step(.01);assert.equal(g.state.energy,68);for(let i=0;i<4;i++){step(1);assert.equal(g.state.energy,66-i*2)}near(g.state.p.burn,0);step(1);assert.equal(g.state.energy,60)});
 test('fire is blocked by protection and invincibility items extinguish ongoing burns',()=>{for(const id of [1,5,6]){reset();g.acquire(id);g.hitPirateFire({});assert.equal(g.state.energy,100);assert.equal(g.state.p.burn,0)}for(const id of [5,6]){reset();g.hitPirateFire({});g.acquire(id);step(5);assert.equal(g.state.energy,70);assert.equal(g.state.p.burn,0)}});
 test('burn can kill or revive without leaving a stale damage timer',()=>{for(const revive of [false,true]){reset();g.state.energy=34;g.state.revive=revive;g.hitPirateFire({});step(2);assert.equal(g.state.mode,revive?'running':'dying');assert.equal(g.state.energy,revive?10:0);if(revive){assert.equal(g.state.p.burn,0);step(2);assert.equal(g.state.energy,10)}}});
 test('desktop starts embedded without fullscreen or history and cleans up after finish',()=>{g.returnToApp();const mobile=sandbox.matchMedia;try{sandbox.matchMedia=query=>({matches:query==='(hover: hover) and (pointer: fine)'});g.start();assert.equal(g.state.nextPortal,90);assert.equal(document.fullscreenElement,null);assert.equal(history.state,null);assert.ok(document.body.classList.contains('desktop-game'));assert.ok(document.body.classList.contains('game-active'));assert.equal(g.state.mode,'running');g.pause();assert.equal(g.state.mode,'paused');g.pause();g.finish();assert.equal(document.body.classList.contains('desktop-game'),false)}finally{sandbox.matchMedia=mobile}});
 test('Escape leaves fullscreen and pauses without discarding the run',()=>{g.state.score=234;step(.1);const t=g.state.t;emit('keydown',{code:'Escape'});assert.equal(document.fullscreenElement,null);assert.equal(document.body.classList.contains('game-active'),false);assert.equal(g.state.mode,'paused');assert.equal(g.state.score,235);step(1);near(g.state.t,t);assert.equal(history.state,null);element('gamePause').onclick();assert.equal(g.state.mode,'running');assert.equal(document.body.classList.contains('game-active'),false)});
 test('phone Back returns to embedded game once, with the run paused',()=>{history.back();assert.equal(g.state.mode,'paused');assert.equal(document.fullscreenElement,null);assert.equal(history.state,null);assert.equal(document.body.classList.contains('game-active'),false)});
 test('native fullscreen exit is observed even when Escape keydown is swallowed',()=>{document.fullscreenElement=null;emit('fullscreenchange');assert.equal(g.state.mode,'paused');assert.equal(document.body.classList.contains('game-active'),false)});
 test('upper-right pause/play freezes and resumes gameplay',()=>{g.hud();assert.equal(element('gamePause').hidden,false);element('gamePause').onclick();step(1);near(g.state.t,0);g.hud();assert.equal(element('gamePause').textContent,'▶ 플레이');element('gamePause').onclick();step(.1);near(g.state.t,.1)});
 test('crocodile frame two grows upward to 180px with a fixed bottom',()=>{g.pattern('gapLong',550);g.state.nextPattern=Infinity;step(.3);g.draw();const calls=drawCalls.filter(a=>a[0].path.startsWith('barrier5'));assert.ok(calls.length);const a=calls.at(-1);assert.equal(a[1],887);assert.equal(a[8],180);assert.equal(a[6],560);assert.equal(a[6]+a[8],740)});
 test('destroying each obstacle grants exactly twenty points once',()=>{g.acquire(5);const o={x:220,y:534,w:80,h:76,type:'low'};g.damage(o);assert.equal(g.state.score,20);assert.equal(g.state.destroyScore,20);assert.equal(g.state.jellyScore,0);g.damage(o);assert.equal(g.state.score,20);g.acquire(6);g.damage({x:220,y:534,w:80,h:76});assert.equal(g.state.score,40)});
 test('tunnel sprites include a complete final tile and destroyed tiles cannot hit again',()=>{g.pattern('slide2');const o=g.state.obstacles[0];o.w=207;o.x=190;o.until=null;g.state.obstacles=[o];const tiles=g.tunnelTiles(o);near(tiles.at(-1).x+tiles.at(-1).w,o.x+o.w);g.draw();const draws=drawCalls.filter(a=>a[0].path.startsWith('barrier1'));assert.equal(draws.length,3);assert.ok(draws.every(a=>a[3]===280.5&&a[7]===69));g.acquire(5);g.damage(o);assert.equal(g.state.destroyScore,20);g.damage(o);assert.equal(g.state.destroyScore,20);g.state.buff[5]=0;g.state.p.inv=0;step(.001);assert.equal(g.state.energy,100)});
 test('speed audio loops for the buff and fades only over its last two seconds',()=>{g.acquire(5);const a=g.soundPlayer.channels.get('speedBuff').audio;assert.equal(a.loop,true);assert.ok(a.src.includes('item_speed.mp3?v=19'));step(5.9);near(a.volume,1);step(1.1);near(a.volume,.5);g.pause();const volume=a.volume;step(2);near(a.volume,volume);assert.ok(a.paused);g.pause();step(1.01);assert.ok(a.paused);assert.equal(g.soundPlayer.channels.has('speedBuff'),false)});
 test('giant effect fires once after growth completes',()=>{g.acquire(6);assert.equal(g.soundPlayer.channels.has('giantEffect'),false);step(.5);const voice=g.soundPlayer.channels.get('giantEffect');assert.ok(voice);assert.ok(g.state.p.scale>=2.9);step(.2);assert.equal(g.soundPlayer.channels.get('giantEffect'),voice)});
 test('goblin rolls exactly 50 percent every seventeen seconds',()=>{for(const [roll,expected] of [[.499,1],[.5,0]]){reset();math.random=()=>roll;g.state.nextGoblin=17;g.state.t=16.999;g.update(.002);assert.equal(g.state.goblins.length,expected);assert.equal(g.state.nextGoblin,34)}});
 test('goblin stops once for two seconds then rushes at four times speed',()=>{math.random=()=>.4;g.spawnGoblin();const m=g.state.goblins[0];assert.ok(m.stopX>=220+1060*.4&&m.stopX<=220+1060*.7);const x=m.x;g.updateGoblins(.1);near(x-m.x,68);while(m.phase==='run')g.updateGoblins(1/120);const stopped=m.x;g.updateGoblins(1.99);near(m.x,stopped);assert.equal(m.phase,'stop');g.pause();step(1);assert.equal(m.phase,'stop');g.pause();g.updateGoblins(.01);assert.equal(m.phase,'rush');assert.ok(g.soundPlayer.channels.has('goblinRun'));g.updateGoblins(.1);near(stopped-m.x,136)});
 test('goblin without a stop stays at double speed and contact costs forty energy',()=>{g.spawnGoblin();const m=g.state.goblins[0];assert.equal(m.willStop,false);m.x=230;g.updateGoblins(.01);assert.equal(g.state.energy,60);g.updateGoblins(.01);assert.equal(g.state.energy,60)});
 test('every monster waits without deleting existing obstacles, traps or jellies',()=>{for(const spawn of [g.spawnPirate,g.spawnIce,g.spawnBaseball,g.spawnGoblin]){reset();g.pattern('low',600);g.pattern('gapShort',900);const obstacles=g.state.obstacles,gaps=g.state.gaps,pickups=g.state.pickups;spawn();assert.equal(g.state.obstacles,obstacles);assert.equal(g.state.gaps,gaps);assert.equal(g.state.pickups,pickups);assert.equal(g.hasSpecialMonster(),false);const x=obstacles[0].x;g.update(.01);near(obstacles[0].x,x-3.4);assert.ok(g.state.encounterQueue.length)}});
 test('portal appears every ninety seconds at thirty-five percent probability and opens inside thirty percent approach',()=>{for(const roll of [0,.349,.35,.999]){reset();math.random=()=>roll;g.state.nextPortal=90;g.state.t=89.99;g.update(.001);assert.equal(g.state.portal,null);g.update(.01);assert.equal(!!g.state.portal,roll<.35);assert.equal(g.state.nextPortal,180);g.state.portal=null;g.state.t=179.999;g.update(.002);assert.equal(!!g.state.portal,roll<.35);assert.equal(g.state.nextPortal,270)}reset();g.spawnPortal();assert.ok(g.soundPlayer.channels.has('portal'));g.state.portal.x=220+1060*.3-1;g.updatePortal(.001);assert.equal(g.state.portal.open,true);g.draw();const a=drawCalls.find(a=>a[0].path.startsWith('portal'));assert.equal(a[1],887);g.state.portal.x=230;g.updatePortal(.001);assert.equal(g.state.bonus.phase,'enter');assert.ok(g.soundPlayer.channels.has('bonusTransition'))});
 test('portal waits for a safe lane while preserving the world',()=>{g.pattern('low',600);const obstacles=g.state.obstacles;g.spawnPortal();assert.equal(g.state.obstacles,obstacles);assert.equal(g.state.pendingPortal,true);assert.equal(g.state.portal,null);for(const o of obstacles)o.x=-200;g.updatePortal(.01);assert.ok(g.state.portal)});
 test('bonus freezes entry for one second, lasts fifteen seconds, restores the exact world',()=>{g.state.t=47;g.state.stage=2;g.state.bg=1234;g.state.distance=567;g.state.p.y=110;g.state.p.vy=240;g.state.p.jumps=1;g.pattern('low',650);g.pattern('gapLong',1000);g.acquire(5);const normal=g.state,obstacle=normal.obstacles[0],gap=normal.gaps[0],pickup=normal.pickups[0],x=obstacle.x,gapX=gap.x,pickupX=pickup.x,buff=normal.buff[5];const speedVoice=g.soundPlayer.channels.get('speedBuff').audio;g.enterBonus();assert.ok(speedVoice.paused);step(.99);assert.equal(g.state,normal);near(g.state.t,47);near(obstacle.x,x);g.jump();near(g.state.p.vy,240);step(.01);assert.notEqual(g.state,normal);assert.equal(g.state.bonus.phase,'active');assert.equal(g.state.obstacles.length,0);assert.equal(g.state.gaps.length,0);assert.equal(g.hasSpecialMonster(),false);assert.ok(g.state.pickups.every(q=>q.type==='bonus'&&q.points===100));assert.ok(g.state.pickups.some(q=>q.y<450));g.pause();step(3);near(g.state.bonus.elapsed,0);g.pause();for(let i=0;i<15*120;i++){g.update(1/120);assert.equal(g.hasSpecialMonster(),false);assert.equal(g.state.obstacles.length,0);if(i%120===0)g.draw()}assert.equal(g.state.bonus.phase,'exit');const score=g.state.score;assert.ok(score>normal.score);g.draw();step(1);assert.equal(g.state,normal);near(obstacle.x,x);near(gap.x,gapX);near(pickup.x,pickupX);near(g.state.bg,1234);near(g.state.distance,567);near(g.state.p.y,110);near(g.state.p.vy,240);near(g.state.t,47);near(g.state.buff[5],buff);assert.equal(g.state.score,score);near(g.state.p.inv,1.5);near(g.state.p.blink,1.5);assert.equal(speedVoice.paused,false);assert.equal(g.state.bonusSeconds,15)});
 test('bonus background rolls both images and all five jelly images stay in bounds',()=>{g.enterBonus();step(1);for(let i=0;i<5;i++){math.random=()=>i/5;g.spawnRareJelly()}for(const q of g.state.pickups)q.x=600;for(const bg of [0,1280,2560]){g.state.bg=bg;g.draw()}assert.ok(drawCalls.some(a=>a[0].path.includes('bonus_bg1')));assert.ok(drawCalls.some(a=>a[0].path.includes('bonus_bg2')));for(let i=1;i<=5;i++)assert.ok(drawCalls.some(a=>a[0].path.includes('bonus_jelly'+i)))});
 test('rare jelly rolls thirty percent every thirty seconds and awards three hundred',()=>{for(const [roll,count] of [[.299,1],[.3,0]]){reset();math.random=()=>roll;g.state.nextBonusJelly=30;g.state.t=29.999;g.update(.002);assert.equal(g.state.pickups.filter(q=>q.type==='bonus').length,count);assert.equal(g.state.nextBonusJelly,60)}reset();g.spawnRareJelly();const q=g.state.pickups[0];q.x=220;q.y=555;g.updatePickups(0);assert.equal(g.state.score,300);assert.equal(g.state.jellyScore,300)});
 test('return protection blocks damage for 1.5 seconds and then expires',()=>{g.enterBonus();step(1);step(15);step(1);g.damage({});assert.equal(g.state.energy,100);step(1.49);g.damage({});assert.equal(g.state.energy,100);step(.02);g.damage({});assert.equal(g.state.energy,75)});
 test('opening speech expires exactly after two seconds',()=>{assert.equal(g.state.speech.text,'\uc545 \uc9c0\uac01\uc774\ub2e4!');step(1.99);assert.ok(g.state.speech);step(.02);assert.equal(g.state.speech,null)});
 test('ordinary jelly gets a 20 percent large variant worth thirteen points',()=>{for(const roll of [.199,.2]){reset();math.random=()=>roll;g.pattern('low');const q=g.state.pickups.find(q=>q.id===1);assert.equal(q.w,roll<.2?39:30);assert.equal(q.large,roll<.2);g.state.pickups=[q];q.x=220;q.y=555;g.updatePickups(0);assert.equal(g.state.jellyScore,roll<.2?13:10)}});
 test('giant speed and travel prediction include its exact expiry',()=>{g.acquire(6);g.update(.01);near(g.state.speed,510);near(g.travelDistance(g.state.t,g.state.t+11),510*9.99+340*1.01);g.acquire(5);g.update(.01);near(g.state.speed,1530);step(10);near(g.state.speed,340)});
 test('goblin pair threshold and one-second delay pause with gameplay',()=>{for(const roll of [.399,.4]){reset();math.random=()=>roll;g.spawnGoblin();assert.equal(g.state.goblins.length,1);step(.99);assert.equal(g.state.goblins.length,1);g.pause();step(2);assert.equal(g.state.goblins.length,1);g.pause();step(.01);assert.equal(g.state.goblins.length,roll<.4?2:1);assert.equal(g.state.goblinFollowup,null)}});
 test('bomb alarm loops on appearance and stops exactly on explosion',()=>{g.spawnBomb();const b=g.state.bombs[0];b.x=1200;step(.01);const alarm=g.soundPlayer.channels.get('bombAlarm').audio;assert.ok(alarm.src.includes('bomb_alram.mp3?v=19'));assert.equal(alarm.loop,true);g.pause();assert.ok(alarm.paused);g.pause();assert.equal(alarm.paused,false);b.x=400;step(.01);assert.equal(b.phase,'igniting');step(.17);assert.equal(b.phase,'exploding');assert.ok(alarm.paused);assert.equal(g.soundPlayer.channels.has('bombAlarm'),false);assert.ok(g.soundPlayer.channels.get('bombExplosion').audio.src.includes('bomb.mp3?v=19'))});
 test('actual pirate projectile collision applies and renders the burn',()=>{g.spawnPirate();const f=g.state.projectiles[0];f.x=240;g.update(.01);near(g.state.energy,70);near(g.state.p.burn,5);burnDraws.length=0;g.draw();assert.ok(burnDraws.some(a=>typeof a[0]==='string'&&a[0].startsWith('\ud654\uc0c1 ')));g.state.pirates=[];g.state.projectiles=[];step(5);near(g.state.p.burn,0)});
 test('bonus runs at one and a half entry speed and uses eight unique layouts',()=>{g.state.speed=510;g.enterBonus();step(1);near(g.state.speed,765);const b=g.state.bonus,seen=new Set([b.lastPattern]);for(let i=0;i<7;i++){b.nextWave=b.elapsed;g.updateBonus(.001);seen.add(b.lastPattern)}assert.equal(seen.size,8);assert.ok(g.state.pickups.every(q=>q.y>250&&q.y<610));const anim=g.state.p.anim;g.updateBonus(.1);near(g.state.p.anim-anim,.15)});
 test('item probability drops three percentage points per stage with a zero floor',()=>{for(const [stage,roll,expected] of [[1,.59,1],[2,.569,1],[2,.571,0],[30,0,0]]){reset();g.state.t=(stage-1)*45;g.state.stage=stage;g.state.nextItems[1]=g.state.t;math.random=()=>roll;g.update(.001);assert.equal(g.state.pickups.filter(q=>q.type==='item').length,expected)}});
 test('mixed bonus threshold is five percent and all five variants award 150',()=>{for(let id=1;id<=5;id++){reset();const rolls=[.049,(id-1)/5,.6];math.random=()=>rolls.shift()??.6;g.pickup('jelly',1,220,555);const q=g.state.pickups[0];assert.equal(q.type,'bonus');assert.equal(q.id,id);assert.equal(q.points,150);assert.equal(q.mixed,true);g.updatePickups(0);assert.equal(g.state.jellyScore,150)}reset();math.random=()=>.05;g.pickup('jelly',1,220,555);assert.equal(g.state.pickups[0].type,'jelly')});
 test('special pirate is exactly twenty percent with larger body flame and sprite',()=>{for(const roll of [.199,.2]){reset();let i=0;math.random=()=>i++===1?roll:.6;g.spawnPirate();const m=g.state.pirates[0],f=g.state.projectiles[0],k=roll<.2?1.4:1;assert.equal(m.special,roll<.2);near(m.w,100*k);near(m.h,145*k);near(f.w,42*k);near(f.h,28*k);g.draw();const a=drawCalls.find(a=>a[0].path.startsWith('monster01'));near(a[7],700*.3*k);near(a[8],650*.3*k)}});
 test('special batter is exactly ten percent with larger body ball and sprite',()=>{for(const roll of [.099,.1]){reset();let i=0;math.random=()=>i++===1?roll:.6;g.spawnBaseball();const m=g.state.batters[0],k=roll<.1?1.3:1;assert.equal(m.special,roll<.1);near(m.w,90*k);near(m.h,155*k);g.fireBaseball(m);near(g.state.baseballs[0].w,64*k);near(g.state.baseballs[0].h,64*k);g.draw();const a=drawCalls.find(a=>a[0].path.startsWith('monster03'));near(a[7],875*.25*k);near(a[8],724*.25*k)}});
 test('special projectile grazing collisions match the enlarged damage area',()=>{for(const special of [false,true]){reset();math.random=()=>special?0:.6;g.spawnPirate();const f=g.state.projectiles[0];f.x=220;f.y=g.box().y-18;g.update(.001);assert.equal(g.state.energy,special?70:100);reset();math.random=()=>special?0:.6;g.spawnBaseball();g.fireBaseball(g.state.batters[0]);const b=g.state.baseballs[0];b.x=220;b.y=g.box().y-30;b.dx=-1;b.dy=0;g.update(.001);assert.equal(g.state.energy,special?60:100)}});
 test('obstacle families unlock by stage and bags reset at transition',()=>{const counts=[];for(let stage=1;stage<=5;stage++){g.state.stage=stage;counts.push(new Set(g.obstaclePool()).size)}assert.deepEqual(counts,[5,8,11,12,12]);g.state.stage=1;g.state.t=10;assert.ok(!g.obstaclePool().includes('stack'));g.nextPatternType();g.state.patternBag=['low'];g.state.stage=4;g.nextPatternType();assert.equal(g.state.patternStage,4);assert.ok(g.state.patternBag.includes('tunnel'))});
 test('jelly layouts unlock without immediate repeats and become richer each stage',()=>{for(const [stage,count] of [[1,3],[2,5],[3,7],[4,8]]){g.state.stage=stage;const names=[];for(let i=0;i<count;i++)names.push(g.nextJellyLayout());assert.equal(new Set(names).size,count);assert.notEqual(g.nextJellyLayout(),names.at(-1))}});
 test('jelly trails stay within jumping reach and outside solid obstacles',()=>{for(let stage=1;stage<=6;stage++)for(const type of ['low','row','stack','air','zigzag','combo'])for(const roll of [.01,.3,.9]){reset();g.state.stage=stage;math.random=()=>roll;g.pattern(type);for(const q of g.state.pickups){assert.ok(q.y>=610-g.constants.JUMP_HEIGHT*2+20);assert.ok(q.y+q.h/2<=610);for(const o of g.state.obstacles){const intersects=q.x-q.w/2<o.x+o.w&&q.x+q.w/2>o.x&&q.y-q.h/2<o.y+o.h&&q.y+q.h/2>o.y;assert.ok(!intersects,stage+' '+type+' '+JSON.stringify(q))}}}});
 test('higher-stage obstacle sequences retain reaction time and recovery floors',()=>{for(const stage of [1,3,5,10])for(const type of ['combo','zigzag']){reset();g.state.stage=stage;g.state.speed=340*Math.pow(1.13,stage-1);g.pattern(type);const obs=g.state.obstacles;for(let i=1;i<obs.length;i++)assert.ok((obs[i].x-obs[i-1].x)/g.state.speed>=1.33);const extent=Math.max(...obs.map(o=>o.x+o.w))-1410;assert.ok(g.state.nextPattern-extent/g.state.speed>=1.5-1e-8);assert.ok(obs.length<=4)}});
 test('special monster bodies remain clearable by timed double jumps through stage five',()=>{for(const stage of [1,3,5])for(const kind of ['pirate','baseball']){let cleared=false;for(const delay of [.5,.7,.9,1.1]){reset();g.state.stage=stage;g.state.t=(stage-1)*45;g.state.speed=340*Math.pow(1.13,stage-1);math.random=()=>0;kind==='pirate'?g.spawnPirate():g.spawnBaseball();const m=(kind==='pirate'?g.state.pirates:g.state.batters)[0];m.x=220+g.state.speed*1.6;m.shots=m.maxShots;m.lastShot=m.swingStart=g.state.t-10;m.phase='obstacle';g.state.projectiles=[];step(delay);g.jump();step(.3);g.jump();step(2.8-delay);if(g.state.energy===100){cleared=true;break}}assert.ok(cleared,kind+' stage '+stage)}});
 test('bomb recoil decays, freezes while paused, and leaves collision bounds unchanged',()=>{g.spawnBomb();const b=g.state.bombs[0];b.phase='exploding';b.age=.04;const bounds=JSON.stringify(g.bombBounds(b)),motion=g.bombMotion(b);assert.ok(Math.hypot(motion.x,motion.y)>0);g.draw();g.pause();step(1);assert.deepEqual(g.bombMotion(b),motion);g.pause();b.age=.8;const late=g.bombMotion(b);assert.ok(Math.hypot(late.x,late.y)<Math.hypot(motion.x,motion.y));assert.equal(JSON.stringify(g.bombBounds(b)),bounds);b.phase='armed';assert.deepEqual({...g.bombMotion(b)},{x:0,y:0,angle:0})});
 console.log(`${count} event and lifecycle checks passed`);
})().catch(error=>{console.error(error);process.exitCode=1});
