'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
class FakeAudio{constructor(src){this.src=src;this.currentTime=0;this.paused=true;this.events=new Map()}addEventListener(k,f){if(!this.events.has(k))this.events.set(k,new Set());this.events.get(k).add(f)}removeEventListener(k,f){this.events.get(k)?.delete(f)}emit(k){for(const f of [...(this.events.get(k)||[])])f()}play(){this.paused=false;return Promise.resolve()}pause(){this.paused=true}}
const sandbox={window:{},Audio:FakeAudio};vm.createContext(sandbox);vm.runInContext(fs.readFileSync('audio.js','utf8'),sandbox);const GameAudio=sandbox.window.GameAudio;let count=0;
function test(name,fn){fn(new GameAudio());console.log('PASS',name);count++}
test('all music and effects resolve to existing nonempty MP3 files',()=>{for(const file of [...GameAudio.music,...Object.values(GameAudio.files)])assert.ok(fs.statSync('bgm/'+file).size>100)});
test('music waits for start and cycles through all four tracks',a=>{assert.ok(a.tracks.every(t=>t.paused));a.startRun();for(let i=0;i<8;i++){assert.equal(a.musicIndex,i%4);assert.equal(a.tracks[a.musicIndex].paused,false);a.tracks[a.musicIndex].emit('ended')}});
test('music uses 70 percent master volume and effects follow master',a=>{a.startRun();a.setVolume(.5);assert.equal(a.tracks[0].volume,.35);const v=a.effect('shield');assert.equal(v.volume,.5);a.setVolume(.8);assert.equal(v.volume,.8)});
test('pause and resume preserve playback positions',a=>{a.startRun();const v=a.effect('frozen');v.currentTime=1;a.tracks[0].currentTime=12;a.pause();assert.ok(v.paused&&a.tracks[0].paused);a.resume();assert.equal(v.currentTime,1);assert.equal(a.tracks[0].currentTime,12);assert.ok(!v.paused&&!a.tracks[0].paused)});
test('mute stops effects and suppresses new sounds',a=>{a.startRun();a.effect('jump');a.setEnabled(false);assert.equal(a.voices.size,0);assert.equal(a.effect('jump'),null);assert.ok(a.tracks[0].paused);a.setEnabled(true);assert.equal(a.tracks[0].paused,false)});
test('baseball sounds play sequentially and cancel cleanly',a=>{a.sequence(['baseballHit','baseballFlight'],{channel:'ball',limits:[.16,.65]});let v=a.channels.get('ball');assert.equal(v.key,'baseballHit');v.audio.currentTime=.17;v.audio.emit('timeupdate');v=a.channels.get('ball');assert.equal(v.key,'baseballFlight');a.stopChannel('ball');v.audio.emit('ended');assert.equal(a.voices.size,0);assert.equal(a.sequences.size,0)});
test('death and game over stop BGM and restart resets first track',a=>{a.startRun();a.nextMusic();a.endRun('death');assert.ok(a.tracks.every(t=>t.paused));assert.equal(a.channels.get('ending').key,'death');a.endRun('gameOver');assert.equal(a.channels.get('ending').key,'gameOver');a.startRun();assert.equal(a.musicIndex,0);assert.equal(a.voices.size,0)});
test('rapid jelly sounds have a bounded voice pool',a=>{for(let i=0;i<100;i++)a.effect('jelly1');assert.equal(a.voices.size,4);assert.equal(a.pools.get('jelly1').length,4)});
test('missing browser audio support does not break gameplay',()=>{const a=new GameAudio({AudioClass:null});a.startRun();a.effect('jump');a.pause();a.resume();a.endRun('gameOver')});
console.log(`${count} audio checks passed`);
